### ISSUE TITLE
Cannot unzip your data

### ISSUE THREAD

**Issue by bjtuweb-12283027** [lilygeorgescu/UBnormal#1]
**Dataset**
We can download your data. But we can not unzip it online/offline. It seems to be damaged(zipfile corrupt). Are there any other options to get access to your dataset?

**Comment by lilygeorgescu** [comment]
Hi,

There is no other option so far to access the dataset, other than the gdrive link.

I checked and the zip file is not damaged.

What OS and unzipping library did you use? There is a problem on linux platform that it cannot unzip files larger than 4GB using unzip, if you use linux you should use 7zip to unzip the file.

Best,
Lili
