### ISSUE TITLE
UBnormal Dataset

### ISSUE THREAD

**Issue by molu-ggg** [lilygeorgescu/UBnormal#10]
Dear author, 
Hello! This data set is very good. I want to do some experiments with this data set. But I have a question about dataset.  I don 't know why the photos in the UBnormal dataset I downloaded are black, but the videos contained in it can be displayed normally. How should I use this dataset properly ? Like this [image](https://raw.githubusercontent.com/molu-ggg/image230306/master/image/imgimage-20230320120742848.png)
I would appreciate it if you could answer. Thank you !

**Comment by lilygeorgescu** [comment]
Hi,

I already answered you in the previous issue. These are the ground-truth segmentation masks which have the id of the object in the position of the object, therefore, the object id being a small number the image seems black, if you open the image in python, you will see that the pixels are not all 0.

Best

**Comment by molu-ggg** [comment]
I do understand , thank you !
