### ISSUE TITLE
all frames are black images in video annotation folder, no matter training and testing 

### ISSUE THREAD

**Issue by GeorgeY1** [lilygeorgescu/UBnormal#11]
Hi
I have an issue that all frame images are totally black in video annotation folders after downloading the dataset.  
![image](https://user-images.githubusercontent.com/58172096/235076834-c3fa8f7f-1712-470f-ac96-b7174fdf76e5.png)

**Comment by lilygeorgescu** [comment]
Please read https://github.com/lilygeorgescu/UBnormal/issues/9 and https://github.com/lilygeorgescu/UBnormal/issues/10 for the explanation.
