### ISSUE TITLE
Dataset: download and expand

### ISSUE THREAD

**Issue by ZhangHuixin1103** [lilygeorgescu/UBnormal#12]
Howdy!

I wanna download and expand your UBnormal.zip, but no matter which method (wget, gdown, manually from google drive) I chose, I continuously faced problems of expanding.

I'm using a macbook with macOS Ventura.

Is the .zip file broken, or am I the only one who cannot open it? Could you please offer another source for downloading?

Your reply will be appreciated. ^^

**Comment by ZhangHuixin1103** [comment]
<img width="626" alt="Screenshot 2023-05-17 at 12 58 04" src="https://github.com/lilygeorgescu/UBnormal/assets/61287150/2517a46a-ff8e-4636-983e-0da0c8edc4e9">
<img width="732" alt="Screenshot 2023-05-17 at 12 59 21" src="https://github.com/lilygeorgescu/UBnormal/assets/61287150/3d5ab504-31f3-4285-8df2-d26e706c39b9">

**Comment by lilygeorgescu** [comment]
Hi,

I do not think that it is a download problem.
Unfortunately, I did not test the archive on Mac, I tested it on Windows and Linux.
However, Linux has a problem with big archives, please see https://github.com/lilygeorgescu/UBnormal/issues/1 for references and fix. MacOS running on Unix,  I think it is the same problem as in the referenced issue.

Best,
Lili

**Comment by ZhangHuixin1103** [comment]
Thanks for your reply. I'll try ^^
