### ISSUE TITLE
Question Regarding AUCROC computation

### ISSUE THREAD

**Issue by yashika-git** [lilygeorgescu/UBnormal#14]
Hello, 

Thanks for the great work!
I had a question regarding the code in ``scripts/compute_auc_score.py``. 
I see 2 AUC values are being computed. Could you please tell if these correspond to the Micro-AUC and Macro-AUC mentioned in the paper? If yes, could you help clarify which one is Micro-AUC and which one is Macro-AUC?

Thank you!

**Comment by lilygeorgescu** [comment]
Hi,

Yes, these correspond to micro and macro AUC, the first one from (https://github.com/lilygeorgescu/UBnormal/blob/8c77642bb72615988ace0451b94ec42f8953a525/scripts/compute_auc_score.py#L28) is micro-AUC while this one (https://github.com/lilygeorgescu/UBnormal/blob/8c77642bb72615988ace0451b94ec42f8953a525/scripts/compute_auc_score.py#L30) is macro-AUC.


Best,
Lili

**Comment by yashika-git** [comment]
Thanks!
