### ISSUE TITLE
A question about the annotation of the benchmark.

### ISSUE THREAD

**Issue by zhihaiguo** [lilygeorgescu/UBnormal#15]
Why are all annotation image masks completely black？So, how to distinguish abnormal areas?
![无标题](https://github.com/lilygeorgescu/UBnormal/assets/59854734/9ec19ed2-9bfb-457d-8bff-76be4dfe71ab)

**Comment by lilygeorgescu** [comment]
Please read https://github.com/lilygeorgescu/UBnormal/issues/9 and https://github.com/lilygeorgescu/UBnormal/issues/10 for the explanation.
