### ISSUE TITLE
How to distinguish normal from abnormal video？

### ISSUE THREAD

**Issue by zhihaiguo** [lilygeorgescu/UBnormal#17]
Thanks for sharing your inspiring work and new dataset.

But in the temporal dimension, there are some frames in the anomalous segments that are normal; also in the spatial dimension, not all of the generated objects added in the anomalous frames are anomalous.

As a pixel-level labeled dataset, how the above problem is coped with?

Thank you very much for considering my request. I look forward to hearing from you soon.

**Comment by lilygeorgescu** [comment]
Hi,

"_But in the temporal dimension, there are some frames in the anomalous segments that are normal_;" -> we tried as much as possible to correctly delimitate the normal vs abnormal segments, meaning that there should not be abnormal annotated segments that contains no anomaly.

"_also in the spatial dimension, not all of the generated objects added in the anomalous frames are anomalous_" -> for each object presented in the scene, we label it accordingly to their anomaly status, meaning that in a frame can appear both  normal and abnormal objects each annotated accordingly to their anomaly status.

Hope this answer your questions.

Best,
Lili

**Comment by zhihaiguo** [comment]
Thank you very much for your reply！But I have a question yet.

In a frame can appear both normal and abnormal objects each annotated accordingly to their anomaly status.---------->But how is this anomalous state represented in the data annotation. Because the labeled mask is binary, only the mask pixel value at the location of the anomalous object will be 1?

**Comment by lilygeorgescu** [comment]
The labeled mask is not binary, it has the id of the object, and if that id appears in the anomaly ids list, it means it is abnormal.

Please read this readme https://github.com/lilygeorgescu/UBnormal/tree/main/scripts#readme for more information.
