### ISSUE TITLE
Hello, I always have a network error when downloading the data set, could you please share a non-Google cloud disk download link with me? thank you

### ISSUE THREAD

**Issue by XinyiWang1123** [lilygeorgescu/UBnormal#18]
Hello, I always have a network error when downloading the data set, could you please share a non-Google cloud disk download link with me? thank you

**Comment by lilygeorgescu** [comment]
Hi,

I am sorry that you cannot download the data set, however, I do not have anywhere else to store the data set, only the Google drive account.
