### ISSUE TITLE
UBNormal Dataset Link - Zip file Broken

### ISSUE THREAD

**Issue by MSiam** [lilygeorgescu/UBnormal#19]
Hello I am writing to report an issue with the zip file provided for UBNormal.zip dataset it seems to have an issue whenever I try to unzip it mentions it is an empty archive. Can you please help with correcting the dataset link?

THank you

**Comment by lilygeorgescu** [comment]
Hi,

What type of OS are you using? I am aware that there is a problem on Linux with big archives, if you are using Linux or Mac, please see https://github.com/lilygeorgescu/UBnormal/issues/1 for references and fix.

**Comment by MSiam** [comment]
No worries I downloaded on Mac OS it works, I was previously trying to unzip it on ubuntu for some weird reason it wasn't able to. But now it is fixed. Thanks
