### ISSUE TITLE
Code for the Paper

### ISSUE THREAD

**Issue by rayush7** [lilygeorgescu/UBnormal#2]
Hi @lilygeorgescu,

Thanks for the great work.
Would you be releasing the code for the model definition, training scripts ?

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work. 

In this work, we did not propose any new method for anomaly detection, we only used available state-of-the-art methods with minor changes (which are described in the paper). So, the code for the methods used in our work is already available online and it is provided by the original authors.

So, please find the code of the method that you need and apply the minor modifications described in our paper.

Best,
Lili
