### ISSUE TITLE
Expand dataset for potential uses on weakly-supervised frameworks 

### ISSUE THREAD

**Issue by aalabree** [lilygeorgescu/UBnormal#22]
The UBnormal datasets is very effective for supervised frameworks and it yeilded good results. **Would it possible to generate the same dataset but without enforced annotation**; this will expand the potential uses of the dataset for weakly-supervised framewors. As for WS no full annotation is required. 

This will enable the Ubnormal dataset to be compared to datasets used in the state-of-the-art frameworks for both supervised and weakly-supervised approaches.

**Comment by lilygeorgescu** [comment]
UBnormal can be used in both settings, it is not mandatory to use the fine-grained annotation, one can use the annotation at the video-level only.
