### ISSUE TITLE
Dataset is not extractable. Showing errors.

### ISSUE THREAD

**Issue by tanimadutta** [lilygeorgescu/UBnormal#5]
After downloading the dataset, tried to extract several times, but it is showing achiving error. Please share the correct dataset.

**Comment by lilygeorgescu** [comment]
Hi,

Please read the answer to this issue https://github.com/lilygeorgescu/UBnormal/issues/1
If you have a different OS and still have this problem, please give me more details about your OS.

I have not encountered any problem with the data set extraction using the right extraction program on Linux or the  Windows OS.

Best,
Lili
