### ISSUE TITLE
great job

### ISSUE THREAD

**Issue by kaigelee** [lilygeorgescu/UBnormal#6]
I would like to ask, how much human and material resources does it take to make a dataset of this size? 

In addition, I would like to ask, what is the hardware environment in which you reproduce the SOTA methods? Such as 8*3090?

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work.
It took us 3 months and a team formed of 5 people working around 3-4 hours a day to create the dataset. For data set generation, we needed a PC with a very good CPU.

The baselines were run on a single 3090 GPU card or a single 1080Ti card depending of the method and the available resources in our lab at that time.

Best,
Lili
