### ISSUE TITLE
why all the pictures are black?

### ISSUE THREAD

**Issue by molu-ggg** [lilygeorgescu/UBnormal#9]
Dear authors , I have a question. I do not why the pictures are black. I have a screenshot photo in [img](https://raw.githubusercontent.com/molu-ggg/image230306/master/image/imgimage-20230319213842483.png)

**Comment by lilygeorgescu** [comment]
Hi,

Those are the segmentation masks with the object id value where the object is placed and the background is 0. Because the object id is a small number, the image seems black, but it s not, if you open it in python/matlab/etc you will see that there are values different than 0.

Best
